FROM nvidia/cuda:12.3.2-cudnn9-devel-ubuntu22.04

# Install Python and other dependencies
RUN apt-get update && \
    apt-get install -y python3 python3-pip git && \
    pip install --upgrade pip && \
    pip3 install pycuda

# Install nano and ffmpeg
RUN apt-get update && \
    apt-get install -y nano

COPY . /workspace
WORKDIR /workspace

CMD [ "tail", "-f", "/dev/null" ]